'use client';

import {
  Bold,
  Clapperboard,
  Code2,
  FilePlus2,
  FileText,
  FolderKanban,
  GitBranchPlus,
  Heading1,
  Heading2,
  Heading3,
  ImagePlus,
  Italic,
  Link2,
  List,
  ListOrdered,
  ListTodo,
  Minus,
  PanelTop,
  Paperclip,
  Pilcrow,
  Quote,
  Strikethrough,
  Underline as UnderlineIcon,
  Workflow,
} from 'lucide-react';
import type { EditorCommand, Translator } from './types';

export function buildEditorCommands(t: Translator): EditorCommand[] {
  return [
    {
      id: 'bold',
      group: 'text',
      label: t('issues.editor.commands.bold'),
      keywords: ['strong', '**'],
      icon: Bold,
      visibility: { toolbar: true, slash: true },
      isActive: (editor) => editor.isActive('bold'),
      run: ({ editor }) => { editor.chain().focus().toggleBold().run(); },
    },
    {
      id: 'italic',
      group: 'text',
      label: t('issues.editor.commands.italic'),
      keywords: ['emphasis', '*'],
      icon: Italic,
      visibility: { toolbar: true, slash: true },
      isActive: (editor) => editor.isActive('italic'),
      run: ({ editor }) => { editor.chain().focus().toggleItalic().run(); },
    },
    {
      id: 'strike',
      group: 'text',
      label: t('issues.editor.commands.strike'),
      keywords: ['~~'],
      icon: Strikethrough,
      visibility: { toolbar: true, slash: true },
      isActive: (editor) => editor.isActive('strike'),
      run: ({ editor }) => { editor.chain().focus().toggleStrike().run(); },
    },
    {
      id: 'underline',
      group: 'text',
      label: t('issues.editor.commands.underline'),
      keywords: ['underline'],
      icon: UnderlineIcon,
      visibility: { toolbar: true, slash: true },
      isActive: (editor) => editor.isActive('underline'),
      run: ({ editor }) => { editor.chain().focus().toggleUnderline().run(); },
    },
    {
      id: 'heading1',
      group: 'headings',
      label: t('issues.editor.commands.heading1'),
      keywords: ['h1', '#', 'heading 1'],
      icon: Heading1,
      visibility: { slash: true, textStyleMenu: true },
      shortcut: { key: '1', code: 'Digit1', ctrl: true, alt: true, display: ['Ctrl', 'Alt', '1'] },
      isActive: (editor) => editor.isActive('heading', { level: 1 }),
      run: ({ editor }) => { editor.chain().focus().toggleHeading({ level: 1 }).run(); },
    },
    {
      id: 'heading2',
      group: 'headings',
      label: t('issues.editor.commands.heading2'),
      keywords: ['h2', '##', 'heading 2'],
      icon: Heading2,
      visibility: { slash: true, textStyleMenu: true },
      shortcut: { key: '2', code: 'Digit2', ctrl: true, alt: true, display: ['Ctrl', 'Alt', '2'] },
      isActive: (editor) => editor.isActive('heading', { level: 2 }),
      run: ({ editor }) => { editor.chain().focus().toggleHeading({ level: 2 }).run(); },
    },
    {
      id: 'heading3',
      group: 'headings',
      label: t('issues.editor.commands.heading3'),
      keywords: ['h3', '###', 'heading 3'],
      icon: Heading3,
      visibility: { slash: true, textStyleMenu: true },
      shortcut: { key: '3', code: 'Digit3', ctrl: true, alt: true, display: ['Ctrl', 'Alt', '3'] },
      isActive: (editor) => editor.isActive('heading', { level: 3 }),
      run: ({ editor }) => { editor.chain().focus().toggleHeading({ level: 3 }).run(); },
    },
    {
      id: 'heading4',
      group: 'headings',
      label: t('issues.editor.commands.heading4'),
      keywords: ['h4', '####', 'heading 4'],
      icon: Heading3,
      visibility: { slash: true, textStyleMenu: true },
      shortcut: { key: '4', code: 'Digit4', ctrl: true, alt: true, display: ['Ctrl', 'Alt', '4'] },
      isActive: (editor) => editor.isActive('heading', { level: 4 }),
      run: ({ editor }) => { editor.chain().focus().toggleHeading({ level: 4 }).run(); },
    },
    {
      id: 'paragraph',
      group: 'headings',
      label: t('issues.editor.commands.paragraph'),
      keywords: ['text', 'regular text'],
      icon: Pilcrow,
      visibility: { slash: true, textStyleMenu: true },
      shortcut: { key: '0', code: 'Digit0', ctrl: true, alt: true, display: ['Ctrl', 'Alt', '0'] },
      isActive: (editor) => editor.isActive('paragraph'),
      run: ({ editor }) => { editor.chain().focus().setParagraph().run(); },
    },
    {
      id: 'bulletList',
      group: 'lists',
      label: t('issues.editor.commands.bulletList'),
      keywords: ['-', '*', 'bulleted list'],
      icon: List,
      visibility: { slash: true },
      shortcut: { key: '8', code: 'Digit8', ctrl: true, shift: true, display: ['Ctrl', 'Shift', '8'] },
      isActive: (editor) => editor.isActive('bulletList'),
      run: ({ editor }) => { editor.chain().focus().toggleBulletList().run(); },
    },
    {
      id: 'orderedList',
      group: 'lists',
      label: t('issues.editor.commands.orderedList'),
      keywords: ['1.', 'numbered list'],
      icon: ListOrdered,
      visibility: { slash: true },
      shortcut: { key: '9', code: 'Digit9', ctrl: true, shift: true, display: ['Ctrl', 'Shift', '9'] },
      isActive: (editor) => editor.isActive('orderedList'),
      run: ({ editor }) => { editor.chain().focus().toggleOrderedList().run(); },
    },
    {
      id: 'taskList',
      group: 'lists',
      label: t('issues.editor.commands.taskList'),
      keywords: ['todo', '[ ]', 'checklist', 'task'],
      icon: ListTodo,
      visibility: { slash: true },
      shortcut: { key: '7', code: 'Digit7', ctrl: true, shift: true, display: ['Ctrl', 'Shift', '7'] },
      isActive: (editor) => editor.isActive('taskList'),
      run: ({ editor }) => { editor.chain().focus().toggleTaskList().run(); },
    },
    {
      id: 'media',
      group: 'insert',
      label: t('issues.editor.commands.media'),
      keywords: ['insert media', 'media', 'image'],
      icon: ImagePlus,
      visibility: { slash: true, placeholder: true },
      run: ({ dispatchBusinessAction }) => dispatchBusinessAction('media'),
    },
    {
      id: 'gif',
      group: 'insert',
      label: t('issues.editor.commands.gif'),
      keywords: ['gif', 'insert gif'],
      icon: Clapperboard,
      visibility: { slash: true, placeholder: true },
      run: ({ dispatchBusinessAction }) => dispatchBusinessAction('gif'),
    },
    {
      id: 'attachment',
      group: 'insert',
      label: t('issues.editor.commands.attachment'),
      keywords: ['attach file', 'file', 'upload'],
      icon: Paperclip,
      visibility: { slash: true, toolbar: true },
      shortcut: { key: 'u', code: 'KeyU', ctrl: true, shift: true, display: ['Ctrl', 'Shift', 'U'] },
      run: ({ dispatchBusinessAction }) => dispatchBusinessAction('attachment'),
    },
    {
      id: 'blockquote',
      group: 'structure',
      label: t('issues.editor.commands.quote'),
      keywords: ['>'],
      icon: Quote,
      visibility: { toolbar: true, menuOnly: true, slash: true },
      isActive: (editor) => editor.isActive('blockquote'),
      run: ({ editor }) => { editor.chain().focus().toggleBlockquote().run(); },
    },
    {
      id: 'codeBlock',
      group: 'structure',
      label: t('issues.editor.commands.codeBlock'),
      keywords: ['```', 'code'],
      icon: Code2,
      visibility: { slash: true, toolbar: true },
      shortcut: { key: '\\', code: 'Backslash', ctrl: true, shift: true, display: ['Ctrl', 'Shift', '\\'] },
      isActive: (editor) => editor.isActive('codeBlock'),
      run: ({ editor }) => { editor.chain().focus().toggleCodeBlock().run(); },
    },
    {
      id: 'diagram',
      group: 'structure',
      label: t('issues.editor.commands.diagram'),
      keywords: ['diagram', 'flowchart'],
      icon: Workflow,
      visibility: { slash: true, placeholder: true },
      run: ({ dispatchBusinessAction }) => dispatchBusinessAction('diagram'),
    },
    {
      id: 'collapsibleSection',
      group: 'structure',
      label: t('issues.editor.commands.collapsibleSection'),
      keywords: ['collapse', 'collapsible', 'details'],
      icon: PanelTop,
      visibility: { slash: true, placeholder: true },
      run: ({ dispatchBusinessAction }) => dispatchBusinessAction('collapsibleSection'),
    },
    {
      id: 'divider',
      group: 'structure',
      label: t('issues.editor.commands.divider'),
      keywords: ['---', 'separator'],
      icon: Minus,
      visibility: { menuOnly: true, slash: true },
      run: ({ editor }) => { editor.chain().focus().setHorizontalRule().run(); },
    },
    {
      id: 'link',
      group: 'structure',
      label: t('issues.editor.commands.link'),
      keywords: ['url', 'hyperlink'],
      icon: Link2,
      visibility: { toolbar: true, slash: true },
      isActive: (editor) => editor.isActive('link'),
      run: ({ openLinkPopover }) => openLinkPopover('selection'),
    },
    {
      id: 'documentRelation',
      group: 'insert',
      label: t('issues.editor.commands.documentRelation'),
      keywords: ['document', 'doc'],
      icon: FileText,
      visibility: { slash: true },
      run: ({ dispatchBusinessAction }) => dispatchBusinessAction('documentRelation'),
    },
    {
      id: 'subIssue',
      group: 'relations',
      label: t('issues.editor.commands.subIssue'),
      keywords: ['child issue'],
      icon: FilePlus2,
      visibility: { slash: true },
      run: ({ dispatchBusinessAction }) => dispatchBusinessAction('subIssue'),
    },
    {
      id: 'relatedIssue',
      group: 'relations',
      label: t('issues.editor.commands.relatedIssue'),
      keywords: ['issue mention', 'relation'],
      icon: GitBranchPlus,
      visibility: { slash: true },
      run: ({ dispatchBusinessAction }) => dispatchBusinessAction('relatedIssue'),
    },
    {
      id: 'projectRelation',
      group: 'relations',
      label: t('issues.editor.commands.projectRelation'),
      keywords: ['project'],
      icon: FolderKanban,
      visibility: { slash: true },
      run: ({ dispatchBusinessAction }) => dispatchBusinessAction('projectRelation'),
    },
  ];
}
