export const queryKeys = {
  issues: (filters?: Record<string, unknown>) => ['issues', filters ?? {}] as const,
  issue: (id: number) => ['issues', id] as const,
  issueDetail: (id: number) => ['issues', id, 'detail'] as const,
  issueByIdentifier: (organizationId: number, identifier: string) => ['issues', organizationId, 'identifier', identifier] as const,
  customFields: (params?: Record<string, unknown>) => ['custom-fields', params ?? {}] as const,
  projects: ['projects'] as const,
  initiatives: ['initiatives'] as const,
  initiativeProjects: (initiativeId: number) => ['initiatives', initiativeId, 'projects'] as const,
  initiativeRelations: (initiativeId: number) => ['initiatives', initiativeId, 'relations'] as const,
  roadmaps: ['roadmaps'] as const,
  roadmapProjects: (roadmapId: number) => ['roadmaps', roadmapId, 'projects'] as const,
  customers: ['customers'] as const,
  customerNeeds: (customerId: number) => ['customers', customerId, 'needs'] as const,
  cycles: ['cycles'] as const,
  projectStatuses: ['project-statuses'] as const,
  customerStatuses: ['customer-statuses'] as const,
  customerTiers: ['customer-tiers'] as const,
  externalEntityInfo: (filters?: Record<string, unknown>) => ['external-entity-info', filters ?? {}] as const,
  externalUsers: (filters?: Record<string, unknown>) => ['external-users', filters ?? {}] as const,
  entityExternalLinks: (filters?: Record<string, unknown>) => ['entity-external-links', filters ?? {}] as const,
  agentActivities: (filters?: Record<string, unknown>) => ['agent-activities', filters ?? {}] as const,
  reactions: (filters?: Record<string, unknown>) => ['reactions', filters ?? {}] as const,
  teams: ['teams'] as const,
  docs: (filters?: Record<string, unknown>) => ['docs', filters ?? {}] as const,
  comments: (filters?: Record<string, unknown>) => ['comments', filters ?? {}] as const,
  activity: (filters?: Record<string, unknown>) => ['activity', filters ?? {}] as const,
  relations: (issueId: number) => ['issues', issueId, 'relations'] as const,
  attachments: (issueId: number) => ['issues', issueId, 'attachments'] as const,
  issueTemplates: (params?: Record<string, unknown>) => ['issue-templates', params ?? {}] as const,
  issueDrafts: (params?: Record<string, unknown>) => ['issue-drafts', params ?? {}] as const,
  recurringIssues: ['recurring-issues'] as const,
  emailIntakeConfigs: ['email-intake', 'configs'] as const,
  dashboard: ['dashboard'] as const,
  dashboardAgent: ['dashboard', 'agent'] as const,
  teamMembers: ['team-members'] as const,
  labels: (params?: Record<string, unknown>) => ['labels', params ?? {}] as const,
  skills: ['skills'] as const,
  skillAnalytics: (name: string) => ['skills', name, 'analytics'] as const,
  views: ['views'] as const,
} as const;
