export const queryKeys = {
  issues: (filters?: Record<string, unknown>) => ['issues', filters ?? {}] as const,
  issue: (id: number) => ['issues', id] as const,
  issueDetail: (id: number) => ['issues', id, 'detail'] as const,
  customFields: (params?: Record<string, unknown>) => ['custom-fields', params ?? {}] as const,
  projects: ['projects'] as const,
  epics: ['epics'] as const,
  sprints: ['sprints'] as const,
  teams: ['teams'] as const,
  docs: (filters?: Record<string, unknown>) => ['docs', filters ?? {}] as const,
  comments: (filters?: Record<string, unknown>) => ['comments', filters ?? {}] as const,
  activity: (filters?: Record<string, unknown>) => ['activity', filters ?? {}] as const,
  relations: (issueId: number) => ['issues', issueId, 'relations'] as const,
  attachments: (issueId: number) => ['issues', issueId, 'attachments'] as const,
  issueTemplates: (params?: Record<string, unknown>) => ['issue-templates', params ?? {}] as const,
  issueDrafts: (params?: Record<string, unknown>) => ['issue-drafts', params ?? {}] as const,
  recurringIssues: ['recurring-issues'] as const,
  emailIntakeConfigs: ['email-intake', 'configs'] as const,
  dashboard: ['dashboard'] as const,
  dashboardAgent: ['dashboard', 'agent'] as const,
  teamMembers: ['team-members'] as const,
  skills: ['skills'] as const,
  skillAnalytics: (name: string) => ['skills', name, 'analytics'] as const,
  views: ['views'] as const,
} as const;
