ALTER TABLE issue DROP COLUMN IF EXISTS epic_id;
ALTER TABLE issue DROP COLUMN IF EXISTS sprint_id;
ALTER TABLE doc DROP COLUMN IF EXISTS epic_id;
ALTER TABLE comment_entry DROP COLUMN IF EXISTS epic_id;

DROP TABLE IF EXISTS epic;
DROP TABLE IF EXISTS sprint;
