apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cruise
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - cruise.example.com
      secretName: cruise-tls
  rules:
    - host: cruise.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: cruise-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cruise-frontend
                port:
                  number: 3000
