ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS protocol VARCHAR(30) NOT NULL DEFAULT 'OIDC';
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS slug VARCHAR(120);
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS scope_level VARCHAR(30) NOT NULL DEFAULT 'GLOBAL';
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS discovery_url VARCHAR(500);
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS end_session_url VARCHAR(500);
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS client_auth_method VARCHAR(50) NOT NULL DEFAULT 'client_secret_post';
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS use_pkce BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS pkce_method VARCHAR(20) NOT NULL DEFAULT 'S256';
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS prompt VARCHAR(50);
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS login_hint_template VARCHAR(255);
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS domain_match_mode VARCHAR(30) NOT NULL DEFAULT 'NONE';
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS allowed_email_domains VARCHAR(1000);
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS enforce_sso BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS account_link_policy VARCHAR(30) NOT NULL DEFAULT 'EMAIL_AUTO_LINK';
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS profile_sync_mode VARCHAR(30) NOT NULL DEFAULT 'FIRST_LOGIN';
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS claim_mapping_json TEXT;
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS button_text VARCHAR(120);
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS button_logo_url VARCHAR(500);
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS display_order INT NOT NULL DEFAULT 0;
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS last_tested_at TIMESTAMP;
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS last_test_result VARCHAR(1000);
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS created_by VARCHAR(100);
ALTER TABLE auth_provider_config ADD COLUMN IF NOT EXISTS updated_by VARCHAR(100);

UPDATE auth_provider_config
SET provider_type = 'OIDC',
    protocol = 'OIDC'
WHERE provider_type IN ('GOOGLE_OIDC', 'ENTERPRISE_OIDC');

ALTER TABLE oauth_login_session ADD COLUMN IF NOT EXISTS code_verifier VARCHAR(255);
ALTER TABLE oauth_login_session ADD COLUMN IF NOT EXISTS redirect_uri VARCHAR(500);
ALTER TABLE oauth_login_session ADD COLUMN IF NOT EXISTS organization_hint BIGINT;
ALTER TABLE oauth_login_session ADD COLUMN IF NOT EXISTS login_hint VARCHAR(255);
ALTER TABLE oauth_login_session ADD COLUMN IF NOT EXISTS requested_scopes VARCHAR(255);
ALTER TABLE oauth_login_session ADD COLUMN IF NOT EXISTS post_login_redirect VARCHAR(500);

ALTER TABLE user_identity ADD COLUMN IF NOT EXISTS issuer VARCHAR(500);
ALTER TABLE user_identity ADD COLUMN IF NOT EXISTS preferred_username VARCHAR(255);
ALTER TABLE user_identity ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE user_identity ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500);
ALTER TABLE user_identity ADD COLUMN IF NOT EXISTS raw_id_token_claims_json TEXT;
ALTER TABLE user_identity ADD COLUMN IF NOT EXISTS raw_userinfo_claims_json TEXT;
ALTER TABLE user_identity ADD COLUMN IF NOT EXISTS linked_at TIMESTAMP;
ALTER TABLE user_identity ADD COLUMN IF NOT EXISTS sync_at TIMESTAMP;

CREATE TABLE IF NOT EXISTS auth_provider_domain (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    email_domain VARCHAR(255) NOT NULL,
    CONSTRAINT uk_auth_provider_domain_email_domain UNIQUE (email_domain)
);
