apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: cruise-git-push-binding
  namespace: pipeline
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.after)
    - name: image-tag
      value: $(extensions.image_tag)
